pygments: true
paginate: 4
auto: true
authors:
  dpilato:
    fullname: David Pilato
    twitter: dadoonet
    github: dadoonet
    gravatar: 20049a614b7f6838dc87b4bc39c42079
    email: david@pilato.fr
  tlrx:
    fullname: Tanguy Leroux
    twitter: tlrx
    github: tlrx
    gravatar: 
    email: 
  filirom1:
    fullname: Romain Philibert
    twitter: Filirom1
    github: Filirom1
    gravatar: 6ac6a4f3b7b0c17631f967054ef6a194
    email:    
navigation:
  - texte: Elasticsearch
    submenu:
    - url: /index.html
      texte: Accueil
    - url: /joinus.html
      texte: Participez
    - url: /agenda.html
      texte: Agenda
  - texte: Trucs et astuces
    submenu:
    - url: /blog.html
      texte: Le blog
      layout: post
#    - url: /tags.html#!débuter
#      texte: Débuter
#    - url: /tags.html#!index
#      texte: Indexer
#    - url: /tags.html#recherche
#      texte: Chercher
#    - url: /tags.html#!avancé
#      texte: Notions Avancées
    - url: /tags.html
      texte: Mots clés
  - texte: Contacts
    submenu:
    - url: /ml.html
      texte: Liste de diffusion
    - url: /twitter.html
      texte: Twitter
    - url: /authors.html
      texte: Les auteurs
