pygments: true
paginate: 4
auto: true
authors:
  dpilato:
    fullname: David Pilato
    twitter: dadoonet
    github: dadoonet
    gravatar: 20049a614b7f6838dc87b4bc39c42079
    email: david@pilato.fr
  tlrx:
    fullname: Tanguy Leroux
    twitter: tlrx
    github: tlrx
    gravatar: 
    email: 
  filirom1:
    fullname: Romain Philibert
    twitter: Filirom1
    github: Filirom1
    gravatar: 6ac6a4f3b7b0c17631f967054ef6a194
    email:    
navigation:
  Elasticsearch:
    Accueil:
      url: /index.html
      texte: Accueil
    Participez:
      url: /joinus.html
      texte: Participez
    Agenda:
      url: /agenda.html
      texte: Agenda
  Trucs:
    Débuter:
      url: notyet
      texte: Débuter
    Indexer:
      url: notyet
      texte: Indexer
    Chercher:
      url: notyet
      texte: Chercher
    Avancé:
      url: notyet
      texte: Notions Avancées
    Tags:
      url: /tags.html
      texte: Mots clés
  Contacts:
    ML:
      url: /ml.html
      texte: Liste de diffusion
    Twitter:
      url: /twitter.html
      texte: Twitter
    Membres:
      url: /authors.html
      texte: Les auteurs
    Blog:
      url: notyet
      texte: Le blog
      layout: post
